baseurl      = "http://swappysh.github.io"
title        = "Swapnil Sharma"
languageCode = "en-us"
theme        = "hello-friend-ng"
publishDir = "docs"

[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  lastModDisplay = "Modified:"

  # Subtitle for home
  homeSubtitle = "Experienced Computer Scientist"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Swapnil Sharma"
  keywords = "homepage, blog"
  images = [""]

  # Custom footer
  # If you want, you can easily override the default footer with your own content.
  #
  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
  footerRight = "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Swapnil Sharma"
    subtitle = "Experienced Computer Scientist"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ bash ./swapnil.sh"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
    [languages.en.params.portrait]
      path = "profile.png"
      alt = "portrait"
      maxWidth = "200px"
    
    # Social icons
    [[params.social]]
      name = "email"
      url  = "mailto:swapnil.sh@nyu.edu"

    [[params.social]]
      name = "github"
      url  = "https://github.com/swappysh"

    [[params.social]]
      name = "linkedin"
      url  = "https://www.linkedin.com/in/swapsharma/"

    [[params.social]]
      name = "twitter"
      url  = "https://twitter.com/mradul_swapnil"

  [menu]
    [[menu.main]]
      identifier = "about_me"
      name       = "About Me"
      url        = "about_me/"

    [[menu.main]]
      identifier = "resume"
      name = "Resume"
      url = "Swapnil_Sharma_ML.pdf"

  # And you can even create generic menu
  # [[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"
